let UserType = {
  SET_USER:"SET_USER",
  SET_USER_RESULTS:"SET_USER_RESULTS",
  SET_PRAYS:"SET_PRAYS",
  SET_PRAY:"SET_PRAY",
  SET_TODAY_LOGS:"SET_TODAY_LOGS",
  SET_YESTERDAY_LOGS:"SET_YESTERDAY_LOGS",
  SET_LAST_SEVEN_DAYS:"SET_LAST_SEVEN_DAYS",
  SET_LAST_30_DAYS:"SET_LAST_30_DAYS"
};

export default UserType;
